# SCRIPT COMMANDS
alias newmatch='python3 ~/.filerep/.scripts/addAtalantaMatch.py'
alias showAtalanta='python3 ~/.filerep/.scripts/atalanta/showAtalanta.py'
alias binary='python3 ~/.terminalscripts/binaryconv.py'
alias timer='python3 ~/.terminalscripts/timer.py'
alias crono='python3 ~/.terminalscripts/cronometro.py'
alias media='python3 ~/.terminalscripts/media.py'
alias password='python3 ~/Desktop/Matteo/Informatica/Python/Password/password.py'
alias filezilla='~/Downloads/FileZilla3/bin/filezilla 2>/dev/null'
alias fetch='~/.terminalscripts/screenfetch-dev'
